### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../DiLiGenT-MV/diligent_mv_pairs.txt'

### ISSUE THREAD

**Issue by xucao-42** [FloralZhao/MVPSNet#1]
Hi, 

When I run your code on DiLiGenT-MV, it reports the file "diligent_mv_paris.txt" is not found.
I think such file is not provided by official DiLiGenT-MV benchmark.

Could you kindly attach this file somewhere or provide some hints to create such a file?

Thank you in advance.

**Comment by xucao-42** [comment]
After creating the following file, the code works anyways.
[diligent_mv_pairs.txt](https://github.com/FloralZhao/MVPSNet/files/13294144/diligent_mv_pairs.txt)

However, another issue regarding the dataset exists.

> FileNotFoundError: [Errno 2] No such file or directory: '../DiLiGenT-MV/mvpmsData/bearPNG/depth/view_01.npy'

Again, the official benchmark does not provide such files. 
Is it possible to share some hints how to prepare such files?

**Comment by xucao-42** [comment]
Hi! 
After rendering the depth map for each view from the GT mesh, it finally works!
I obtained meshes (left) quite similar to that in the paper (right). And it only took 34 secs per object on my machine (one RTX 4090Ti).

<img width="1666" alt="Screen Shot 2023-11-08 at 18 15 29" src="https://github.com/FloralZhao/MVPSNet/assets/28819074/22d86dfc-147f-46da-a66c-375d829ff0d8">

However, I am quite uncertain why depth maps are required to infer depth maps from multi-view images?
Could you share some motivations behind this operation?
Thanks!

**Comment by FloralZhao** [comment]
Hi, thank you for pointing it out. Depth maps are not needed. You can just delete the code related to depth map loading in datasets/diligent_mv.py. We once loaded them for internal reference and forgot to clean up.
